# Generated by Django 5.2.6 on 2025-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Shop', max_length=100)),
                ('active_header', models.CharField(choices=[('header1', 'Header 1 - Logo Left, Menu Middle, Icons Right'), ('header2', 'Header 2 - Menu Left, Logo Middle, Icons Right'), ('header3', 'Header 3 - Centered Logo with Bottom Menu'), ('header4', 'Header 4 - Minimal with Side Menu')], default='header1', max_length=20)),
                ('support_email', models.EmailField(default='support@myshop.com', max_length=254)),
                ('phone_number', models.CharField(default='+1234567890', max_length=20)),
                ('address', models.TextField(default='Your address here')),
            ],
        ),
    ]
