# Generated by Django 5.2.6 on 2025-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_footer',
            field=models.CharField(choices=[('footer1', 'Footer 1 - Dark & Modern'), ('footer2', 'Footer 2 - Light & Clean'), ('footer3', 'Footer 3 - App & Newsletter'), ('footer4', 'Footer 4 - Bold & Primary')], default='footer1', max_length=20),
        ),
    ]
