# Generated by Django 5.2.6 on 2025-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footertemplate_headertemplate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='support_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='phone_number',
            new_name='contact_phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default='Your trusted ecommerce partner'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_footer',
            field=models.CharField(choices=[('footer1', 'Footer 1 - Dark Modern'), ('footer2', 'Footer 2 - Light Clean'), ('footer3', 'Footer 3 - App Style'), ('footer4', 'Footer 4 - Bold Primary')], default='footer1', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_header',
            field=models.CharField(choices=[('header1', 'Header 1 - Classic'), ('header2', 'Header 2 - Modern'), ('header3', 'Header 3 - Minimal'), ('header4', 'Header 4 - Centered')], default='header1', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123 Business Street, City, Country'),
        ),
    ]
