# Generated by Django 5.2.6 on 2025-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_emailtemplate_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='custom_js',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_short',
            field=models.CharField(blank=True, help_text='Short address for headers', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bing_webmaster',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_hours',
            field=models.TextField(blank=True, help_text='Format: Monday-Friday: 9AM-6PM'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_js_footer',
            field=models.TextField(blank=True, help_text='JavaScript added before closing body'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_js_header',
            field=models.TextField(blank=True, help_text='JavaScript added in head'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_guest_checkout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_user_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_wishlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year business was established', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_message',
            field=models.TextField(blank=True, default="We're currently performing maintenance. Please check back soon."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='site/og/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sales_email',
            field=models.EmailField(blank=True, help_text='Sales email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo_dark',
            field=models.ImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to='site/logo/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_moto',
            field=models.CharField(blank=True, help_text='Short tagline or motto', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_slogan',
            field=models.TextField(blank=True, help_text='Longer description or slogan'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='timezone',
            field=models.CharField(default='UTC', help_text='e.g., America/New_York', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(default='123 Business Street, City, Country'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='support@myshop.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='+1234567890', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/favicon/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_analytics',
            field=models.TextField(blank=True, help_text='GA4 Measurement ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='My Shop', max_length=100),
        ),
    ]
