# Generated by Django 5.2.6 on 2025-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSetting',
            new_name='DefaultSiteSetting',
        ),
        migrations.AlterModelOptions(
            name='defaultsitesetting',
            options={'verbose_name': 'Default Site Setting', 'verbose_name_plural': 'Default Site Settings'},
        ),
    ]
